//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grupo8_Proyecto
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AhorcadoContext : DbContext
    {
        public AhorcadoContext()
            : base("name=AhorcadoContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Letra> Letras { get; set; }
        public virtual DbSet<Palabra> Palabras { get; set; }
        public virtual DbSet<Partida> Partidas { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
