//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grupo8_Proyecto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Letra
    {
        public int let_id { get; set; }
        public string let_letra { get; set; }
        public Nullable<bool> let_escorrecta { get; set; }
        public int par_id { get; set; }
    
        public virtual Partida Partida { get; set; }
    }
}
