//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grupo8_Proyecto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Letra
    {
        public int let_id { get; set; }
        public string let_letra { get; set; }
        public Nullable<bool> let_escorrecta { get; set; }
        public int par_id { get; set; }
    
        public virtual Partida Partida { get; set; }
    }
}
