//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grupo8_Proyecto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Palabra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Palabra()
        {
            this.Partidas = new HashSet<Partida>();
        }
    
        public int pal_id { get; set; }
        public string pal_texto { get; set; }
        public int pal_longitud { get; set; }
        public Nullable<bool> pal_tilde { get; set; }
        public string pal_inicial { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Partida> Partidas { get; set; }
    }
}
