//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grupo8_Proyecto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partida
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partida()
        {
            this.Letras = new HashSet<Letra>();
        }
    
        public int par_id { get; set; }
        public string par_nivel { get; set; }
        public string par_resultado { get; set; }
        public Nullable<System.DateTime> par_fecha { get; set; }
        public int usu_id { get; set; }
        public int pal_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Letra> Letras { get; set; }
        public virtual Palabra Palabra { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
