//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grupo8_Proyecto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partida
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partida()
        {
            this.Letras = new HashSet<Letra>();
        }
    
        public int par_id { get; set; }
        public string par_nivel { get; set; }
        public string par_resultado { get; set; }
        public Nullable<System.DateTime> par_fecha { get; set; }
        public int usu_id { get; set; }
        public int pal_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Letra> Letras { get; set; }
        public virtual Palabra Palabra { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
